### ISSUE TITLE
Request: Add build instruction

### ISSUE THREAD

**Issue by YukihoAA** [HerpDerpinstine/VRCBhapticsIntegration#10]
Hi, I'd like to contribute to this project but idk how to build :(

I'd be happy If you add building intruction for people who have interested in this project.

thank you. :)

**Comment by HerpDerpinstine** [comment]
When I get to uploading the new update I will add that to the README.

**Comment by HerpDerpinstine** [comment]
https://github.com/HerpDerpinstine/VRCBhapticsIntegration/blob/main/README.md#compilation
