### ISSUE TITLE
Doesn't seem to be working for me

### ISSUE THREAD

**Issue by GingasVRFO** [HerpDerpinstine/VRCBhapticsIntegration#12]
Mod seems to be loading in the game, but the haptics aren't going off for some reason.

I has worked previously, and I even tried reuploading my avatar with the haptics and going to the bhaptics world... but it doesn't seem to be working for me

**Comment by shackhorn** [comment]
yup, seems to be broken with new vrc update

**Comment by HerpDerpinstine** [comment]
It isn't broken.
It has a few bugs but I can assure you its not broken.
I already know it has issues which is why I am already working on an update.
