### ISSUE TITLE
Cannot spawn in VRChat with VRCBhaptics Avatars (Instant Crash)

### ISSUE THREAD

**Issue by Zeregiro** [HerpDerpinstine/VRCBhapticsIntegration#6]
I been having this issue ongoing since May VRChat update. Troubleshooting a lot on my own. I was waiting for a new version of this mod to see if it resolves my issue which I had no luck. I used the new 1.0.5 dll + Melonloader 0.4 and re-uploaded my avatar with the latest VRCBhaptics Unity package. 

For the first time today, I was able to spawn in VR with the haptics suit working completely fine for a few minutes which it didn't work before. Afterwards, VRChat crashes once and now whenever I try to log back in with the same VRCBhaptics Avatar, the game instantly crashes when it attempts to load the avatar in. This is the same issue I had from May VRChat update to today. If I attempt to clear the cache, I can spawn in the VRChat world while I am downloading my avatar but once the download completes, the game instantly crash. Whats odd is that if I go in via Desktop VRChat, the VRCbhaptics avatar loads completely fine and the haptics suit responses to all haptics. If i go back to VR mode, the same issue occurs where it instantly crashes the game as soon as I load in. 

If I uninstall all mods, Melonloader, remove cache, and reinstall Vanilla VRChat, I can replicate the crashing issue with the VRCBhaptics Avatar with Vanilla VRchat. If I go to Unity, 2018.4.20f1, and re-upload the exact same avatar without the VRCBhaptics Integration then the avatar loads fine without any crashing issues. If I upload any other different VRChat avatars, I can replicate the exact same issues as above.  I do apologize if this is a bit information overload but I wanted to explain all the different troubleshooting steps that I have done so far and explain how weird this issue is. 

I will attached log files for the Latest Melonloader files for, VR with all my mods, and Reinstalling melonloader with just VRCbhaptics mod only on VR, Desktop mode with all my mods (worked fine),

[Latest-VR_with othermods.log](https://github.com/HerpDerpinstine/VRCBhapticsIntegration/files/6678721/Latest-VR_with.othermods.log)
[Latest-VR only vrcbhaptics mod.log](https://github.com/HerpDerpinstine/VRCBhapticsIntegration/files/6678723/Latest-VR.only.vrcbhaptics.mod.log)
[Latest-Desktop with other mods.log](https://github.com/HerpDerpinstine/VRCBhapticsIntegration/files/6678724/Latest-Desktop.with.other.mods.log)

As for specs on my computer: 
Windows 10 - 21H2
Intel i9-10900K 
Nvidia RTX3090
32 GB of RAM

**Comment by GotCarrots** [comment]
did you find any fix yet?
I am having the same issue

**Comment by HerpDerpinstine** [comment]
This is a **known** rare issue.
Please stop trying to DM me about it.
I will work on it when I actually have a chance to.
