### ISSUE TITLE
the following component types are found on the avatar and will be removed by the client : BhapticsVRCeditor

### ISSUE THREAD

**Issue by jinxyUwU** [HerpDerpinstine/VRCBhapticsIntegration#8]
i followed the youtube video and the avatar is ready to upload, but the sdk forces you to remove all b haptics mods and files in the project. i was told to disable pipeline manager but had the same issue. i heard there were compatibility issues and i was unable to find a fix. is it still possible to upload avatars with this mod?

**Comment by HerpDerpinstine** [comment]
Yes.
You just didn't click Finish on the component.

**Comment by HerpDerpinstine** [comment]
https://youtu.be/duaOPZsA5A0
